In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


## Vectorization demo

In [8]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("vectorized version" + str(1000*(toc-tic))+"ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("for loop version" + str(1000*(toc-tic))+"ms")

249819.350052
vectorized version1.783132553100586ms
249819.350052
for loop version515.3648853302002ms


## broadcasting example

In [11]:
A = np.array([[56,0,4.4,68],
            [1.2,104,52,8],
            [1.8,135,99,0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [12]:
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [13]:
percentage = A/cal.reshape(1,4)*100
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


## python-numpy vectors

In [14]:
a = np.random.randn(5)

In [15]:
print(a)

[ 0.5223318   1.07351992 -0.81120706 -0.70155743 -1.27560769]


In [16]:
print(a.shape)
# rank 1 array

(5,)


In [17]:
print(a.T)

[ 0.5223318   1.07351992 -0.81120706 -0.70155743 -1.27560769]


In [18]:
print(np.dot(a,a.T))

4.20269022627


In [21]:
a = np.random.randn(5,1)
print(a)

[[ 0.32825823]
 [-1.73692914]
 [-1.30088704]
 [-0.6280314 ]
 [-0.92986419]]


In [22]:
print(a.T)

[[ 0.32825823 -1.73692914 -1.30088704 -0.6280314  -0.92986419]]


In [23]:
print(np.dot(a,a.T))

[[ 0.10775346 -0.57016128 -0.42702687 -0.20615647 -0.30523557]
 [-0.57016128  3.01692285  2.25954862  1.09084603  1.61510821]
 [-0.42702687  2.25954862  1.6923071   0.8169979   1.20964828]
 [-0.20615647  1.09084603  0.8169979   0.39442343  0.58398391]
 [-0.30523557  1.61510821  1.20964828  0.58398391  0.86464741]]
